# Generated by Django 5.0.1 on 2024-01-10 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('T shirt', 'T shirt'), ('Jeans', 'Jeans'), ('Shirt', 'Shirt'), ('BABY DRESS', 'BABY DRESS'), ('Kurta Salwar', 'Kurta Salwar'), ('burkha', 'Burkha'), ('lehenga', 'Lehenga')], max_length=12)),
                ('image', models.ImageField(null=True, upload_to='product/images/')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('sylhet', 'sylhet'), ('mymenshing', 'mymenshing'), ('chittagong', 'chittagong'), ('Barishal', 'Barishal'), ('khulna', 'khulna'), ('rangpur', 'rangpur'), ('rajshahi', 'rajshahi')], max_length=200)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('upazila', models.CharField(blank=True, max_length=150)),
                ('contact', models.IntegerField()),
                ('village_road', models.CharField(blank=True, max_length=150)),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('deleted', 'deleted'), ('accepted', 'accepted'), ('On The way', 'On the way')], default='pending', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
